# Generated by Django 4.1.7 on 2023-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbit',
            name='name',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AlterField(
            model_name='fitbit',
            name='refresh_token',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
