# Generated by Django 4.1.7 on 2023-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('kbis', models.CharField(max_length=255)),
                ('refreshToken', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
