# Generated by Django 4.1.7 on 2023-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlefit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
